# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(641, 426)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spidernameEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spidernameEdit.sizePolicy().hasHeightForWidth())
        self.spidernameEdit.setSizePolicy(sizePolicy)
        self.spidernameEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spidernameEdit.setObjectName("spidernameEdit")
        self.horizontalLayout.addWidget(self.spidernameEdit)
        self.urlseedEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.urlseedEdit.setObjectName("urlseedEdit")
        self.horizontalLayout.addWidget(self.urlseedEdit)
        self.publishButton = QtWidgets.QPushButton(self.centralwidget)
        self.publishButton.setMinimumSize(QtCore.QSize(100, 0))
        self.publishButton.setObjectName("publishButton")
        self.horizontalLayout.addWidget(self.publishButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(560, 80))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_loss = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_loss.sizePolicy().hasHeightForWidth())
        self.label_loss.setSizePolicy(sizePolicy)
        self.label_loss.setObjectName("label_loss")
        self.gridLayout.addWidget(self.label_loss, 2, 3, 1, 1)
        self.pages = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pages.sizePolicy().hasHeightForWidth())
        self.pages.setSizePolicy(sizePolicy)
        self.pages.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pages.setObjectName("pages")
        self.gridLayout.addWidget(self.pages, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 2, 3, 1)
        self.tps = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tps.sizePolicy().hasHeightForWidth())
        self.tps.setSizePolicy(sizePolicy)
        self.tps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tps.setObjectName("tps")
        self.gridLayout.addWidget(self.tps, 0, 4, 1, 1)
        self.label_tps = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_tps.sizePolicy().hasHeightForWidth())
        self.label_tps.setSizePolicy(sizePolicy)
        self.label_tps.setObjectName("label_tps")
        self.gridLayout.addWidget(self.label_tps, 0, 3, 1, 1)
        self.items = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.items.sizePolicy().hasHeightForWidth())
        self.items.setSizePolicy(sizePolicy)
        self.items.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.items.setObjectName("items")
        self.gridLayout.addWidget(self.items, 1, 1, 1, 1)
        self.loss_balacing = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loss_balacing.sizePolicy().hasHeightForWidth())
        self.loss_balacing.setSizePolicy(sizePolicy)
        self.loss_balacing.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.loss_balacing.setObjectName("loss_balacing")
        self.gridLayout.addWidget(self.loss_balacing, 2, 4, 1, 1)
        self.speed = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speed.sizePolicy().hasHeightForWidth())
        self.speed.setSizePolicy(sizePolicy)
        self.speed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speed.setObjectName("speed")
        self.gridLayout.addWidget(self.speed, 1, 4, 1, 1)
        self.label_speed = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_speed.sizePolicy().hasHeightForWidth())
        self.label_speed.setSizePolicy(sizePolicy)
        self.label_speed.setObjectName("label_speed")
        self.gridLayout.addWidget(self.label_speed, 1, 3, 1, 1)
        self.label_counts = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_counts.sizePolicy().hasHeightForWidth())
        self.label_counts.setSizePolicy(sizePolicy)
        self.label_counts.setObjectName("label_counts")
        self.gridLayout.addWidget(self.label_counts, 2, 0, 1, 1)
        self.label_items = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_items.sizePolicy().hasHeightForWidth())
        self.label_items.setSizePolicy(sizePolicy)
        self.label_items.setObjectName("label_items")
        self.gridLayout.addWidget(self.label_items, 1, 0, 1, 1)
        self.label_pages = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pages.sizePolicy().hasHeightForWidth())
        self.label_pages.setSizePolicy(sizePolicy)
        self.label_pages.setObjectName("label_pages")
        self.gridLayout.addWidget(self.label_pages, 0, 0, 1, 1)
        self.node_counts = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.node_counts.sizePolicy().hasHeightForWidth())
        self.node_counts.setSizePolicy(sizePolicy)
        self.node_counts.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.node_counts.setObjectName("node_counts")
        self.gridLayout.addWidget(self.node_counts, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout.addWidget(self.tableWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 641, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.spidernameEdit.setText(_translate("MainWindow", "test"))
        self.urlseedEdit.setText(_translate("MainWindow", "http://"))
        self.publishButton.setText(_translate("MainWindow", "发布"))
        self.label_loss.setText(_translate("MainWindow", "负载失衡:"))
        self.pages.setText(_translate("MainWindow", "0个"))
        self.tps.setText(_translate("MainWindow", "0个/s"))
        self.label_tps.setText(_translate("MainWindow", "处理速度:"))
        self.items.setText(_translate("MainWindow", "0个"))
        self.loss_balacing.setText(_translate("MainWindow", "0"))
        self.speed.setText(_translate("MainWindow", "0KB/s"))
        self.label_speed.setText(_translate("MainWindow", "下载速度:"))
        self.label_counts.setText(_translate("MainWindow", "节点个数:"))
        self.label_items.setText(_translate("MainWindow", "处理数量:"))
        self.label_pages.setText(_translate("MainWindow", "抓取页面:"))
        self.node_counts.setText(_translate("MainWindow", "0个"))

